{% extends 'layout.phtml' %}

{% block body %}
<div class="row">
      <body class="booking">
          <div class="box">
              <h1>Book a game!</h1>
              <form method="post" class="round_input">
                      <input type="text" name="firstname" placeholder="First name">
                      <input type="text" name="lastname" placeholder="Last name">
                      <input type="email" name="email" placeholder="Email">
                      <input type="number" name="phone"  placeholder="Phone number">
                      <input id="datepicker" name ="date" placeholder=" Choose a date" bookings= {{booked}}>
                      <textarea id="textarea_message" rows="3" cols="50" name="info" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;" >Optional information</textarea>
                      <ul class="button-group round">
                        <input id="button" type="submit" class="button success" value="Submit">
                        <input id="button" type="reset" class="button alert" value="Reset">
                      </ul><br>
              </form>
          </div>
      </body>
</div>
{% endblock %}
