{% extends 'layout.phtml' %}

{% block body %}
<!DOCTYPE html>
<div class="row">
    <body class="login">
        <div class="box">
            <h1>Citygame</h1>
            <form method="post">
                    <input id="key_field" type="text" name="key" placeholder="Enter key here" autofocus="true">
                    <input id="button" type="submit" class="button radius" value="Submit">
            </form>
        </div>
    </body>
</div>
{% endblock %}
